### ISSUE TITLE
Package being tested not installed in the correct directory on first execution

### ISSUE THREAD

**Issue by zirus2402** [pdm-project/tox-pdm#25]
Hi,

I'm having an issue where my project is installed under `__pypackages__3.10/lib/bin/` instead of `__pypackages__3.10/bin/` when running tox for the first time in a clean environment. 

This causes the following error when executing the code from the project entry point:
`[PdmUsageError]: Command 'test-project' is not found on your PATH.`.

Running tox once more (with the `-r` flag) moves the package in the correct directory, and the error goes away.

`pyproject.toml`
```toml
[project]
name = "project"
version = "1.0"
description = "Test project"
authors = [
    {name = "Jonathan Chouinard", email = "jchouinard@dimonoff.com"},
]
dependencies = [
    "click>=8.1.3",
]
requires-python = ">=3.8"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
tox = [
  "tox",
  "tox-pdm",
]

[project.scripts]
test-project = "project.main:cli"

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
```
`tox.ini`
```ini
[tox]
basepython = py38

[testenv]
commands =
    test-project
```
`main.py`
```python
from __future__ import annotations

import click


@click.command()
def cli():
    print("YAY")
```
